// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgS3rZFBt7kJD-7bGQK3U3mpq-fDTqKgE',
    appId: '1:960892806421:web:356d7c9626dc24f295751c',
    messagingSenderId: '960892806421',
    projectId: 'project-hack-3d75d',
    authDomain: 'project-hack-3d75d.firebaseapp.com',
    storageBucket: 'project-hack-3d75d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIthDmWdoL0A_vAKu8sdaIks8sgy5vc_4',
    appId: '1:960892806421:android:45b546042d32e16a95751c',
    messagingSenderId: '960892806421',
    projectId: 'project-hack-3d75d',
    storageBucket: 'project-hack-3d75d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Am7fFmMY9Zhsct9IM0p1iXj4YwWp_nE',
    appId: '1:960892806421:ios:d8ac20311696a27695751c',
    messagingSenderId: '960892806421',
    projectId: 'project-hack-3d75d',
    storageBucket: 'project-hack-3d75d.firebasestorage.app',
    iosBundleId: 'com.example.finalHackathonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4Am7fFmMY9Zhsct9IM0p1iXj4YwWp_nE',
    appId: '1:960892806421:ios:d8ac20311696a27695751c',
    messagingSenderId: '960892806421',
    projectId: 'project-hack-3d75d',
    storageBucket: 'project-hack-3d75d.firebasestorage.app',
    iosBundleId: 'com.example.finalHackathonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgS3rZFBt7kJD-7bGQK3U3mpq-fDTqKgE',
    appId: '1:960892806421:web:e4a213a0f63c905395751c',
    messagingSenderId: '960892806421',
    projectId: 'project-hack-3d75d',
    authDomain: 'project-hack-3d75d.firebaseapp.com',
    storageBucket: 'project-hack-3d75d.firebasestorage.app',
  );
}
